---
title: "Taller de R: Estadística y Programación"
date: '16/08/2023'
pagetitle: "Taller 1"
output: 
       pdf_document: default
---

<!-- Configuracion de la consola de R -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T , eval = T , warning = T)
```

En este taller se evalúan los temas vistos en las clases 1 a 3 del curso. Lea atentamente las instrucciones del taller.

<!----------------------------------------------------------------------------->

```{=tex}
\begin{center} \textcolor{blue}{\subsection{Instrucciones}} \end{center}
```
-   Este taller pesa el **20%** de la nota total del curso y podrá responderlo de manera individual o en grupo de hasta 3 personas. 

- Debe crear un script en el que almacene las respuestas del problem-set. Asigné su código al nombre del archivo. Por ejemplo `201725852.R`.

- En las primeras líneas del script debe escribir su nombre, código y la versión de R sobre la que está trabajando.

-   Por favor sea lo más organizado posible y comente paso a paso cada línea de código, pero recuerden **NO** usar ningún acento o carácter especial dentro del código para evitar problemas al abrir los scripts en los diferentes sistemas operativos.

-   **Cada integrante** del grupo deberá colgar en Bloque Neón el script del problem-set antes de las 23:59 horas del **31 de agosto de 2023**.

-   No seguir las instrucciones tiene una penalización del **20%** de la nota final.

<!----------------------------------------------------------------------------->
```{=tex}
\begin{center} \textcolor{blue}{\section{Problem-set}} \end{center}
```

<!----------------->
\section{Introducción a R: Operadores y Funciones}

\begin{itemize}
\item \textbf{Operadores aritméticos:} Realize una operación que calcule el resultado de \(7\) elevado a la potencia de \(3\).

\item \textbf{Operador lógico:} Escribe un ejemplo de una expresión que utilice un operador lógico para verificar si el valor de \(2\) es mayor que \(10\).

\item \textbf{Instalación y llamada de una librería:} Instala y llama a la librería \texttt{dplyr} en R. Puede usar la librería `pacman` o alternativamente, utilize las funciones \texttt{install.packages()} y \texttt{require()}.

\item \textbf{Obtener información sobre una función:} Utilizando la función de ayuda, obtén información sobre la función \texttt{sum()} y muestra un ejemplo de cómo se usa.
\end{itemize}

<!----------------->
\section{Fundamentos de programación: Objetos y Workspace}

\begin{itemize}
\item \textbf{Creación y eliminación de objetos en el workspace:} Crea un objeto llamado \texttt{mi\_numero} y asígnale el valor numérico \(25\) y otro obeto llamado \texttt{mi\_numero\_2} que sea igual al objeto \texttt{mi\_numero} a la potencia de \(2\). Ahora elimine el objeto \texttt{mi\_numero} del workspace utilizando las funciones vistas en clase.

\item \textbf{Mostrar lista de objetos en el workspace:} Muestra el código que permite imprimir la lista de todos los objetos disponibles en el workspace.

\item \textbf{Guardar el contenido del workspace en un archivo:} Explica con un ejemplo cómo se guarda el contenido del workspace en un archivo llamado \texttt{"backup.RData"}. (**Hint:** Use la función \texttt{save.image()})
\end{itemize}

<!----------------->
\section{Estructura de datos en R: Vectores y Dataframes}

\begin{itemize}
\item \textbf{Creación de un vector:} Cree un vector llamado \texttt{mi\_vector} que contenga los nombres de los días de la semana.

\item \textbf{Creación de una matriz numérica:} Defina una matriz \texttt{mi\_matriz} de \(3\) filas y \(2\) columnas con valores numéricos de tu elección.

\item \textbf{Creación de un dataframe y acceso a columna:} Cree un dataframe llamado \texttt{mi\_dataframe} con dos columnas: "nombre" y "edad", y agrega algunos datos.

\item \textbf{Tibbles:} Convierta \texttt{mi\_dataframe} en un tibble y muestra cómo se accede a la columna "nombre".
\end{itemize}

<!----------------->
\section{Estructura de datos en R: Listas y Manipulación}

\begin{itemize}
\item \textbf{Creación de una lista:} Genere una lista llamada \texttt{mi\_lista} que contenga un vector numérico, un dataframe y un valor lógico.

\item \textbf{Acceso a elementos de una lista:} Explique con un ejemplo cómo acceder al segundo elemento del vector dentro de \texttt{mi\_lista}.

\item \textbf{Combinación de listas:}
Combina las listas \texttt{lista1} y \texttt{lista2} en una nueva lista llamada \texttt{lista\_combinada}.

\item \textbf{Lista de listas:} Crea una lista de listas donde cada elemento sea una lista que contenga un vector de nombres y un dataframe.
\end{itemize}



